version: '3.7'

services:
  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - "5432:5432"

  # backend:
  #   build: ./backend
  #   env_file:
  #     - .env
  #   ports:
  #     - "${BACKEND_PORT}:${BACKEND_PORT}"
  #   depends_on:
  #     - db
  #   environment:
  #     - BACKEND_PORT=${BACKEND_PORT}
  #     # - POSTGRES_HOST=${POSTGRES_HOST}
  #     - DATABASE_URL=${DATABASE_URL}
  #   command: bash -c "alembic upgrade head && python /app/app.py"

  frontend:
    image: frontend
    build: .
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    command: run /app/app.py --server.address 0.0.0.0 --server.port ${FRONTEND_PORT}
    volumes:
      - ./videos:/app/videos
