"""Initial migration

Revision ID: 600032c0cb7d
Revises: 
Create Date: 2024-08-23 09:08:56.602938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '600032c0cb7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'rtsp_streams',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('url', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_rtsp_streams_id'), 'rtsp_streams', ['id'], unique=False)
    op.create_index(op.f('ix_rtsp_streams_url'), 'rtsp_streams', ['url'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rtsp_streams_url'), table_name='rtsp_streams')
    op.drop_index(op.f('ix_rtsp_streams_id'), table_name='rtsp_streams')
    op.drop_table('rtsp_streams')
